### ISSUE TITLE
JSON version is too strict

### ISSUE THREAD

**Issue by Antoinemarteau** [bauglir/Kroki.jl#64]
The JSON version in Project.toml depends on DocStringExtensions.jl version 0.8 (incompatible with 0.9), which is not compatible with Julia 1.12. 
Using Kroki currently prevents me from updating DocStringExtensions v0.9, breaking my Documenter.makdoc on Julia 1.12

I tried to fork & update Kroki but tests didn't pass :'( I don't know if someone can update Kroki.

The error (those MethodList field renaming happened in Julia 1.12):
```
┌ Error: parsedoc failed to parse a docstring into Markdown. This indicates a problem with the docstring.
│   exception = FieldError: type Base.MethodList has no field `mt`, available fields: `ms`, `tn`
│   docstr.data =
│    Dict{Symbol, Any} with 5 entries:
│      :typesig    => Tuple{AbstractMatrix}
│      :module     => Gridap.Arrays
│      ⋮           => ⋮
│   collect(docstr.text) =
│    2-element Vector{Any}:
│     DocStringExtensions.MethodSignatures()
│     "\n"
│   docstr.object = nothing
└ @ Documenter.DocSystem ~/.julia/packages/Documenter/AXNMp/src/DocSystem.jl:289
```

**Comment by bauglir** [comment]
Thanks for reporting! I'm not actively using `Kroki` at the moment myself and its pretty low maintenance, so I hadn't run into this myself 😅

So the working theory is that `DocStringExtensions` is not pulling versions past v0.9.4 due to the `compat` bound on `JSON`. To make things work on Julia v1.12 the fix in JuliaDocs/DocStringExtensions.jl#176 needs to be pulled in, which is in `DocStringExtensions@0.9.5`. I cannot seem to be able to get into a state where v0.9.5 does _not_ get pulled in on v1.12 thohugh, but I'll investigate a bit further.

In any case, I have the tests already fixed, they broke due to changes in the diagram renders behind the Kroki service. The fix should be simple, but I would like to root cause the dependencies a bit.

**Comment by bauglir** [comment]
The fixes in #65 should resolve the issues you are seeing. Unfortunately, there appear to be some CI infrastructure issues preventing me from merging and releasing this. I will keep an eye on that and release the fixes as soon as possible. In the meantime, you can unblock yourself by temporarily depending on the branch for the PR.  Do note that the branch will get deleted as soon as the PR merges, so that could cause some disruption between the PR merging and the release propagating.

**Comment by Antoinemarteau** [comment]
Thanks for looking at this !

**Comment by bauglir** [comment]
Took a bit to get this into a release due to the infrastructure outage, but this should be available through General soon!
